"""added parentId, children fields update 2

Revision ID: 012e5eb3d86e
Revises: 15378ad7a85d
Create Date: 2022-07-24 01:51:15.147066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012e5eb3d86e'
down_revision = '15378ad7a85d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
