"""fix problem with migration on DateTime field

Revision ID: 01c6bdc13351
Revises: d872c35be7cd
Create Date: 2022-07-24 04:16:24.135176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c6bdc13351'
down_revision = '1c0f421c51d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ShopUnit', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ShopUnit', 'date')
    # ### end Alembic commands ###
