"""added parentId, children fields update

Revision ID: 15378ad7a85d
Revises: 21b3b7573a5d
Create Date: 2022-07-24 01:41:23.913311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15378ad7a85d'
down_revision = '21b3b7573a5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ShopUnit_id'), 'ShopUnit', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ShopUnit_id'), table_name='ShopUnit')
    # ### end Alembic commands ###
