"""want to store datetime in database

Revision ID: 43269a7c851f
Revises: 6eb3fc0e49c3
Create Date: 2022-07-24 04:04:30.566196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43269a7c851f'
down_revision = '6eb3fc0e49c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
