"""fix problem with migration on DateTime field

Revision ID: 4fb9bc4103d8
Revises: 1c0f421c51d7
Create Date: 2022-07-24 04:15:05.433102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb9bc4103d8'
down_revision = '1c0f421c51d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ShopUnit', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
