"""want to store datetime in database

Revision ID: 75d9937ebdf7
Revises: d9eeec695206
Create Date: 2022-07-24 03:53:38.292997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d9937ebdf7'
down_revision = 'd9eeec695206'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
