"""fix problem with migration on DateTime field

Revision ID: d872c35be7cd
Revises: 4fb9bc4103d8
Create Date: 2022-07-24 04:15:49.881107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd872c35be7cd'
down_revision = '4fb9bc4103d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
