"""deleted children field, added index on FK

Revision ID: d9eeec695206
Revises: 012e5eb3d86e
Create Date: 2022-07-24 02:59:08.957035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9eeec695206'
down_revision = '15378ad7a85d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ShopUnit_id', table_name='ShopUnit')
    op.create_index(op.f('ix_ShopUnit_parentId'), 'ShopUnit', ['parentId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ShopUnit_parentId'), table_name='ShopUnit')
    op.create_index('ix_ShopUnit_id', 'ShopUnit', ['id'], unique=False)
    # ### end Alembic commands ###
